### ISSUE TITLE
TypeError: Cannot call method 'on' of null

### ISSUE THREAD

**Issue by njam** [cargomedia/socket-redis#41]
```
[2013-06-28 02:17:52.854] [ERROR] [default] - Uncaught exception: TypeError: Cannot call method 'on' of null
TypeError: Cannot call method 'on' of null
    at Server.<anonymous> (/usr/lib/node_modules/socket-redis/lib/worker.js:147:15)
    at Server.EventEmitter.emit (events.js:95:17)
    at App.emit (/usr/lib/node_modules/socket-redis/node_modules/sockjs/lib/sockjs.js:182:27)
    at Session.emit_open (/usr/lib/node_modules/socket-redis/node_modules/sockjs/lib/transport.js:107:23)
    at process._tickCallback (node.js:415:13)
```

**Comment by njam** [comment]
Waiting on cargomedia/puppet-cargomedia#719

**Comment by tomaszdurka** [comment]
We have no errors in socket-redis logs anymore.
This code is quite old.
This bug is most likely fixed.
Let's close this.
